Feature/enable-gulmc-update-model-settings-for-hazard
OasisLMF/OasisPiWind pull request #120
Opened 2023-02-23 10:52 UTC by mtazzari

2023-02-23 10:55 UTC, mtazzari commented
Some tests will fail because the new oasislmf schema has not been merged yet. We need to merge this PR first so that all tests in PR https://github.com/OasisLMF/OasisLMF/pull/1181 in oasislmf pass

2023-02-23 10:57 UTC, mtazzari commented
Tests:
- PiWind MDK / run_mdk (3.8) (pull_request)  fails because it uses oasislmf with the old schema.
- PiWind MDK / run_mdk (3.9) (pull_request)  fails because it uses oasislmf with the old schema.
- PiWind Testing / PiWind Integration / Check Results (pull_request)  fails because of a bug in ods tools and in the need to update the tests in oasislmf. 

So, it is expected that we need to merge this PR with these three tests failing.

2023-02-23 14:52 UTC, sambles commented
We should manually run the failing tests with the correct branches set before merging
* https://github.com/OasisLMF/OasisPiWind/actions/runs/4253798862 
piwind: `feature/enable-gulmc-update-model-settings-for-hazard` vs oasislmf: `feature/gulmc-haz-correlation-v2` 

* https://github.com/OasisLMF/OasisPiWind/actions/runs/4253823265
piwind: `feature/enable-gulmc-update-model-settings-for-hazard` vs oasislmf: `feature/gulmc-haz-correlation-v2`

2023-02-23 15:05 UTC, sambles requested changes
Test case 2 is failing:

```
tests/test_piwind_integration.py::case_2::test_output_file[/home/runner/work/OasisPiWind/OasisPiWind/tests/ci/expected/2_case/output/gul_S1_aalcalc-csv] FAILED [ 19%]
tests/test_piwind_integration.py::case_2::test_output_file[/home/runner/work/OasisPiWind/OasisPiWind/tests/ci/expected/2_case/output/gul_S1_eltcalc-csv] FAILED [ 19%]
tests/test_piwind_integration.py::case_2::test_output_file[/home/runner/work/OasisPiWind/OasisPiWind/tests/ci/expected/2_case/output/gul_S1_leccalc_full_uncertainty_aep-csv] FAILED [ 20%]
tests/test_piwind_integration.py::case_2::test_output_file[/home/runner/work/OasisPiWind/OasisPiWind/tests/ci/expected/2_case/output/gul_S1_leccalc_full_uncertainty_oep-csv] FAILED [ 20%]
tests/test_piwind_integration.py::case_2::test_output_file[/home/runner/work/OasisPiWind/OasisPiWind/tests/ci/expected/2_case/output/gul_S1_summary-info-csv] PASSED [ 21%]
tests/test_piwind_integration.py::case_2::test_output_file[/home/runner/work/OasisPiWind/OasisPiWind/tests/ci/expected/2_case/output/il_S1_aalcalc-csv] FAILED [ 21%]
tests/test_piwind_integration.py::case_2::test_output_file[/home/runner/work/OasisPiWind/OasisPiWind/tests/ci/expected/2_case/output/il_S1_eltcalc-csv] FAILED [ 22%]
tests/test_piwind_integration.py::case_2::test_output_file[/home/runner/work/OasisPiWind/OasisPiWind/tests/ci/expected/2_case/output/il_S1_leccalc_full_uncertainty_aep-csv] FAILED [ 22%]
tests/test_piwind_integration.py::case_2::test_output_file[/home/runner/work/OasisPiWind/OasisPiWind/tests/ci/expected/2_case/output/il_S1_leccalc_full_uncertainty_oep-csv] FAILED [ 23%]
tests/test_piwind_integration.py::case_2::test_output_file[/home/runner/work/OasisPiWind/OasisPiWind/tests/ci/expected/2_case/output/il_S1_summary-info-csv] PASSED [ 23%]
```
See: https://github.com/OasisLMF/OasisPiWind/actions/runs/4253798862/jobs/7399159426

2023-03-01 08:45 UTC, mtazzari commented
Re-running pipeline with test case 2 after fix in gulmc:
https://github.com/OasisLMF/OasisPiWind/actions/runs/4253798862

2023-03-01 09:06 UTC, sambles approved these changes

2023-03-01 09:16 UTC, mtazzari commented
The three failing tests

- PiWind MDK / run_mdk (3.8) (pull_request) Failing after 1m
- PiWind Testing / PiWind Integration / Check Results (pull_request) Failing after 4m
- PiWind MDK / run_mdk (3.9) (pull_request) Failing after 1m

are expected to fail because use the `develop` branch of oasislmf.
We manually ran these tests on the `feature/enable-gulmc-update-model-settings-for-hazard` branch of oasislmf (see [this comment](https://github.com/OasisLMF/OasisPiWind/pull/120#issuecomment-1449585191)) and they pass.
We can thus merge this PR.

2023-03-01 09:51 UTC, sstruzik approved these changes

2023-03-01 09:55 UTC, johcarter approved these changes

2023-03-01 10:11 UTC, merged

2023-03-14 16:54 UTC, kenzilan commented
Hello, OASIS Team

When I tried to run the Oasis MDK on Colab (Python 3.9, pip oasislmf, OasisPiWind.git clone), the MDK still fails with same error as quoted below


> ```
> RUNNING: oasislmf.manager.interface
> 
> JSON Validation error in 'model_settings.json': {
>     "data_settings": [
>         "Additional properties are not allowed ('damage_group_fields', 'hazard_group_fields' were unexpected)"
>     ]


![image](https://user-images.githubusercontent.com/48265542/225078246-70c7e7c1-00db-464e-b32e-68a57554d2ae.png)

What should I do in order to make this MDK running? Thank you

2023-03-14 17:07 UTC, sambles commented
Hi @kenzilan  we're just about to run a new oasislmf release (today or tomorrow).

The current `develop` branch of piwind isn't aligned with the last published oasislmf pip package, so the until then Colab will fail with that error. 

 **Workaround:**  add a command to pip install oasislmf from its `develop` branch
 
 ```
 !pip install -v git+https://git@github.com/OasisLMF/OasisLMF.git@develop#egg=oasislmf[extra]
 ```